# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, serialize=False)),
                ('account', models.CharField(max_length=12)),
            ],
        )
    ]
